# site settings
title: sdeehub.github.io
subtitle: /aroi
email: aroi.sdee.co@gmail.com
description: Cooked & Eaten by SDEE's
baseurl: "/aroi" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 328/139 Soi Sannibathedsabal Ladprao Road
city: Chankasem Jatuchuk
state: Bangkok
zip_code: 10900
country: Thailand
phone: 0.954.639.444

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
